/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as CompteRouteImport } from './routes/compte'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LivraisonRouteImport } from './routes/livraison'
import { Route as NouveautesRouteImport } from './routes/nouveautes'
import { Route as PaiementRouteImport } from './routes/paiement'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as RetoursRouteImport } from './routes/retours'
import { Route as SuiviRouteImport } from './routes/suivi'
import { Route as CategorieSlugRouteImport } from './routes/categorie.$slug'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRoute = CompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LivraisonRoute = LivraisonRouteImport.update({
  id: '/livraison',
  path: '/livraison',
  getParentRoute: () => rootRouteImport,
} as any)
const NouveautesRoute = NouveautesRouteImport.update({
  id: '/nouveautes',
  path: '/nouveautes',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementRoute = PaiementRouteImport.update({
  id: '/paiement',
  path: '/paiement',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const RetoursRoute = RetoursRouteImport.update({
  id: '/retours',
  path: '/retours',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviRoute = SuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorieSlugRoute = CategorieSlugRouteImport.update({
  id: '/categorie/$slug',
  path: '/categorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/cgu': typeof CguRoute
  '/compte': typeof CompteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/livraison': typeof LivraisonRoute
  '/nouveautes': typeof NouveautesRoute
  '/paiement': typeof PaiementRoute
  '/panier': typeof PanierRoute
  '/promotions': typeof PromotionsRoute
  '/recherche': typeof RechercheRoute
  '/retours': typeof RetoursRoute
  '/suivi': typeof SuiviRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/cgu': typeof CguRoute
  '/compte': typeof CompteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/livraison': typeof LivraisonRoute
  '/nouveautes': typeof NouveautesRoute
  '/paiement': typeof PaiementRoute
  '/panier': typeof PanierRoute
  '/promotions': typeof PromotionsRoute
  '/recherche': typeof RechercheRoute
  '/retours': typeof RetoursRoute
  '/suivi': typeof SuiviRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/cgu': typeof CguRoute
  '/compte': typeof CompteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/livraison': typeof LivraisonRoute
  '/nouveautes': typeof NouveautesRoute
  '/paiement': typeof PaiementRoute
  '/panier': typeof PanierRoute
  '/promotions': typeof PromotionsRoute
  '/recherche': typeof RechercheRoute
  '/retours': typeof RetoursRoute
  '/suivi': typeof SuiviRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/cgu'
    | '/compte'
    | '/confidentialite'
    | '/confirmation'
    | '/contact'
    | '/faq'
    | '/livraison'
    | '/nouveautes'
    | '/paiement'
    | '/panier'
    | '/promotions'
    | '/recherche'
    | '/retours'
    | '/suivi'
    | '/categorie/$slug'
    | '/produit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/cgu'
    | '/compte'
    | '/confidentialite'
    | '/confirmation'
    | '/contact'
    | '/faq'
    | '/livraison'
    | '/nouveautes'
    | '/paiement'
    | '/panier'
    | '/promotions'
    | '/recherche'
    | '/retours'
    | '/suivi'
    | '/categorie/$slug'
    | '/produit/$slug'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/cgu'
    | '/compte'
    | '/confidentialite'
    | '/confirmation'
    | '/contact'
    | '/faq'
    | '/livraison'
    | '/nouveautes'
    | '/paiement'
    | '/panier'
    | '/promotions'
    | '/recherche'
    | '/retours'
    | '/suivi'
    | '/categorie/$slug'
    | '/produit/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BoutiqueRoute: typeof BoutiqueRoute
  CguRoute: typeof CguRoute
  CompteRoute: typeof CompteRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConfirmationRoute: typeof ConfirmationRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LivraisonRoute: typeof LivraisonRoute
  NouveautesRoute: typeof NouveautesRoute
  PaiementRoute: typeof PaiementRoute
  PanierRoute: typeof PanierRoute
  PromotionsRoute: typeof PromotionsRoute
  RechercheRoute: typeof RechercheRoute
  RetoursRoute: typeof RetoursRoute
  SuiviRoute: typeof SuiviRoute
  CategorieSlugRoute: typeof CategorieSlugRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte': {
      id: '/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livraison': {
      id: '/livraison'
      path: '/livraison'
      fullPath: '/livraison'
      preLoaderRoute: typeof LivraisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nouveautes': {
      id: '/nouveautes'
      path: '/nouveautes'
      fullPath: '/nouveautes'
      preLoaderRoute: typeof NouveautesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement': {
      id: '/paiement'
      path: '/paiement'
      fullPath: '/paiement'
      preLoaderRoute: typeof PaiementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retours': {
      id: '/retours'
      path: '/retours'
      fullPath: '/retours'
      preLoaderRoute: typeof RetoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi': {
      id: '/suivi'
      path: '/suivi'
      fullPath: '/suivi'
      preLoaderRoute: typeof SuiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorie/$slug': {
      id: '/categorie/$slug'
      path: '/categorie/$slug'
      fullPath: '/categorie/$slug'
      preLoaderRoute: typeof CategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BoutiqueRoute: BoutiqueRoute,
  CguRoute: CguRoute,
  CompteRoute: CompteRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConfirmationRoute: ConfirmationRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LivraisonRoute: LivraisonRoute,
  NouveautesRoute: NouveautesRoute,
  PaiementRoute: PaiementRoute,
  PanierRoute: PanierRoute,
  PromotionsRoute: PromotionsRoute,
  RechercheRoute: RechercheRoute,
  RetoursRoute: RetoursRoute,
  SuiviRoute: SuiviRoute,
  CategorieSlugRoute: CategorieSlugRoute,
  ProduitSlugRoute: ProduitSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
